In [1]:
import numpy as np
#import boto3
import tensorflow as tf
import pandas as pd
import os
import csv
#import cStringIO
#! sudo /mnt1/anaconda2/bin/pip install s3fs
#! sudo pip install s3fs
#import s3fs
#pd.options.display.max_columns = None
#pd.options.display.max_rows = None

In [6]:
b = pd.read_csv(filepath_or_buffer='/Users/bambi/Downloads/ml-20m/movies.csv')

In [5]:
c = pd.read_csv('/Users/bambi/Downloads/ml-20m/ratings.csv')

In [10]:
tr = c.groupby('userId')

In [13]:
tr_2 = tr.count()

In [14]:
tr_2

        movieId  rating  timestamp
userId
1           175     175        175
2            61      61         61
3           187     187        187
4            28      28         28
5            66      66         66
6            24      24         24
7           276     276        276
8            70      70         70
9            35      35         35
10           38      38         38
11          504     504        504
12           36      36         36
13           62      62         62
14          243     243        243
15           49      49         49
16           60      60         60
17           26      26         26
18          121     121        121
19           50      50         50
20           28      28         28
21          163     163        163
22          133     133        133
23          102     102        102
24          506     506        506
25          121     121        121
26           61      61         61
27           69      69         69
28           32      32         32
29          177     177        177
30           31      31         31
...         ...     ...        ...
138464      241     241        241
138465       33      33         33
138466       32      32         32
138467      298     298        298
138468       31      31         31
138469       22      22         22
138470       99      99         99
138471      143     143        143
138472      352     352        352
138473       90      90         90
138474      594     594        594
138475      144     144        144
138476       26      26         26
138477      224     224        224
138478       41      41         41
138479       35      35         35
138480       21      21         21
138481       30      30         30
138482       40      40         40
138483      276     276        276
138484      148     148        148
138485       34      34         34
138486      193     193        193
138487       62      62         62
138488       24      24         24
138489       38      38         38
138490      151     151        151
138491       22      22         22
138492       82      82         82
138493      373     373        373

[138493 rows x 3 columns]

In [17]:
tr_3 = tr_2.sort_values('movieId', ascending=False).reset_index()

In [18]:
top_users = tr_3.iloc[:1000, :]['userId']

In [19]:
top_users

0      118205
1        8405
2       82418
3      121535
4      125794
5       74142
6       34576
7      131904
8       83090
9       59477
10     130767
11      79159
12       8963
13      15617
14      92011
15      71975
16      20132
17      46470
18      88820
19      63147
20     130459
21     120575
22       9544
23      31122
24      18611
25     125978
26      18138
27      91193
28     111549
29      68026
        ...
970     64150
971     14678
972    120312
973    124998
974     69829
975    127840
976     58170
977     57398
978     87094
979    127871
980    118344
981     42913
982     70770
983    132509
984      9197
985     18069
986     68060
987    123817
988     25960
989     92706
990     49024
991      2568
992     18471
993    114531
994    134156
995     15616
996     74241
997     80989
998     22352
999     87746
Name: userId, Length: 1000, dtype: int64

In [22]:
users_w_rate = c.loc[c['userId'].isin(top_users)]

In [25]:
users_w_rate_sorted = users_w_rate.sort_values(['userId', 'timestamp'])

In [26]:
users_w_rate_sorted

          userId  movieId  rating   timestamp
20611        156     2028     5.0  1037060604
20402        156     1387     5.0  1037060737
21617        156     4529     4.0  1037060737
20044        156      450     4.0  1037060765
21227        156     3501     4.0  1037060765
20207        156      902     4.0  1037142460
21889        156     5431     3.0  1037142460
21629        156     4550     3.0  1037142533
20926        156     2748     3.0  1037142578
21110        156     3180     2.0  1037142578
21777        156     4975     5.0  1037142578
20294        156     1127     5.0  1037143389
20961        156     2826     5.0  1037143389
20972        156     2858     5.0  1037143389
21242        156     3534     5.0  1037143389
21323        156     3754     3.0  1037143389
21412        156     3986     4.0  1037143389
21680        156     4639     3.0  1037143389
20901        156     2699     5.0  1037143446
20906        156     2707     4.0  1037143446
20962        156     2827     4.0  1037143446
21450        156     4052     4.0  1037143446
21035        156     2997     3.0  1037143497
21153        156     3285     4.0  1037143497
21234        156     3516     5.0  1037143497
21263        156     3593     3.0  1037143497
20907        156     2710     1.0  1037143567
20939        156     2771     4.0  1037143567
20993        156     2908     3.0  1037143567
21038        156     3005     5.0  1037143567
...          ...      ...     ...         ...
19979714  138325    86892     4.5  1350349952
19978971  138325     6870     4.0  1350349968
19978123  138325      661     4.5  1350350025
19978383  138325     1913     4.5  1350350303
19978236  138325     1192     4.5  1350350347
19979583  138325    62511     4.0  1350350397
19979520  138325    52579     4.5  1350350403
19978965  138325     6852     4.5  1350350428
19978357  138325     1599     1.5  1350350514
19978599  138325     3176     4.0  1350350646
19978479  138325     2396     4.0  1352440783
19978092  138325      380     4.5  1352440789
19979323  138325    27831     4.5  1352440814
19978401  138325     1955     4.5  1352440845
19979135  138325     8464     4.0  1352441006
19979604  138325    66758     4.5  1352441016
19979625  138325    69640     3.0  1352441053
19979618  138325    69027     4.0  1352441068
19979496  138325    49422     4.0  1352441069
19979193  138325    25746     4.5  1352441081
19979015  138325     7079     4.5  1352441083
19979218  138325    25798     4.5  1352441111
19978697  138325     3928     4.0  1352441150
19979733  138325    93865     4.5  1352441167
19979699  138325    81417     2.0  1352441188
19978998  138325     7036     3.0  1352441198
19979223  138325    25822     4.0  1352441209
19979723  138325    89761     4.0  1352441219
19979428  138325    41863     4.5  1352441227
19978976  138325     6909     4.5  1352441236

[1819672 rows x 4 columns]